In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("cirrhosis.csv")

In [38]:
df.dropna(inplace=True)

In [39]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()
Status=le.fit_transform(df['Status'])
Drug=le.fit_transform(df['Sex'])
Sex=le.fit_transform(df['Sex'])
Ascites=le.fit_transform(df['Ascites'])
Hepatomegaly=le.fit_transform(df['Hepatomegaly'])
Spiders=le.fit_transform(df['Spiders'])
Edema=le.fit_transform(df['Edema'])

dic={
    'Status':Status,
     'Drug':Drug,
     'Sex':Sex,
     'Ascites':Ascites,
      'Hepatomegaly':Hepatomegaly,
     'Spiders':Spiders,
     'Edema':Edema
}
df1=pd.DataFrame(dic)
df1

Status  Drug  Sex  Ascites  Hepatomegaly  Spiders  Edema
0         2     0    0        1             1        1      2
1         0     0    0        0             1        1      0
2         2     1    1        0             0        0      1
3         2     0    0        0             1        1      1
4         1     0    0        0             1        1      0
..      ...   ...  ...      ...           ...      ...    ...
271       0     0    0        0             1        0      0
272       0     0    0        0             0        0      0
273       0     0    0        0             0        0      0
274       0     0    0        0             0        0      0
275       0     0    0        0             0        1      0

[276 rows x 7 columns]

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler=StandardScaler()

In [42]:
X_scaled=scaler.fit_transform(df1.iloc[:,:19])
Y=df.iloc[:,19]



In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,Y,test_size=0.3,random_state=0)

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
knn = KNeighborsClassifier(n_neighbors=5)

In [47]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [48]:
ypredict=knn.predict(X_test)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix

In [50]:
print((confusion_matrix(y_test,ypredict)))

[[ 0  0  4  0]
 [ 0  1 14  3]
 [ 0  7 22  4]
 [ 0 10  8 10]]


In [51]:
print((classification_report(y_test,ypredict)))
print(metrics.mean_squared_error(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         4
         2.0       0.06      0.06      0.06        18
         3.0       0.46      0.67      0.54        33
         4.0       0.59      0.36      0.44        28

    accuracy                           0.40        83
   macro avg       0.28      0.27      0.26        83
weighted avg       0.39      0.40      0.38        83



C:\Users\anshu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\anshu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\anshu\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


NameError: name 'metrics' is not defined